version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Herzlich wilkommen
      - run:
          name: Print the Current Time
          command: date